### ISSUE TITLE
 v1.4.1 not showing the green completion mark

### ISSUE THREAD

**Issue by gygith** [dsarman/logseq-plugin-better-tasks#1]
Hello,

I just updated from v1.4.0 to v1.4.1 and realized that the green completion mark that was showing before with each completion is not showing anymore. Can you please check or advise on how to fix this problem? Thanks much!

Best,
Guang

**Comment by dsarman** [comment]
Hi, please try if version [v1.4.2](https://github.com/dsarman/logseq-plugin-better-tasks/compare/v1.4.1...v1.4.2) solves your problem.

**Comment by gygith** [comment]
Yes, the new version 1.4.2 fixed the issue. Many thanks!
